services:
  backend:
    build: ./Backend
    ports:
      - "8080:3000"
    volumes:
      - ./Backend:/app
      - backend_node_modules:/app/node_modules
    command: npx nodemon -L server.js


volumes:
  backend_node_modules: